[tool.pylint.master]
extension-pkg-whitelist = ["homeassistant"]

[tool.pylint.messages_control]
disable = [
    "import-error",
    "missing-module-docstring", 
    "missing-class-docstring",
    "missing-function-docstring",
    "too-few-public-methods",
    "unused-argument",
    "broad-except"
]

[tool.pyright]
include = ["custom_components"]
ignore = ["**/__pycache__"]
reportMissingImports = false
reportMissingModuleSource = false
reportOptionalMemberAccess = false
reportOptionalSubscript = false
reportPrivateImportUsage = false
pythonVersion = "3.11"
typeCheckingMode = "basic"

[tool.black]
line-length = 100
target-version = ['py311']
include = '\.pyi?$'
extend-exclude = '''
/(
  __pycache__
)/
'''
