default_config:

wattbox:
  - host: !secret wattbox_ip
    name: wattbox
    scan_interval: 00:00:05
    username: !secret wattbox_username
    password: !secret wattbox_password

logger:
  default: info
  logs:
    custom_components.wattbox: debug
