name: Release

on:
  release:
    types:
      - published

permissions: {}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Adjust version number
        shell: bash
        run: |
          yq -i -o json '.version="${{ github.event.release.tag_name }}"' \
            "${{ github.workspace }}/custom_components/wattbox/manifest.json"

      - name: Zip the integration directory
        shell: bash
        run: |
          cd "${{ github.workspace }}/custom_components/wattbox"
          zip hass-wattbox.zip -r ./

      - name: Upload zip to the release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 # v2.2.2
        with:
          files: ${{ github.workspace }}/custom_components/wattbox/hass-wattbox.zip
